// The Blackfin CLI ⇄ app protocol (#61). Shared, verbatim, between three
// processes: the `blackfin` CLI (a Node process an agent spawns), the Electron
// main process (the socket server), and the renderer (the dispatcher). It is
// pure — no I/O, no `net`, no `fs` — so all three can import it and a test can
// exercise the whole contract without a socket.
//
// The contract this file fixes is inherited unchanged by every later command
// (#62–#65, #70), so the shapes here are deliberately small and closed.

/** The one protocol version this build speaks. Bumped only on a breaking change. */
export const CLIProtocolVersion = 1

/** A single request is at most this many bytes on the wire, rejected before parse. */
export const MaxRequestBytes = 64 * 1024

/**
 * Every failure an agent can be told about, as a closed set. The agent
 * distinguishes "app not open" from "I called it wrong" from "refused" by the
 * code and its exit status — never by parsing the message.
 */
export type CLIErrorCode =
  | 'usage' // exit 2
  | 'unknown-command' // exit 2
  | 'unauthorized' // exit 3
  | 'rate-limited' // exit 3
  | 'app-not-running' // exit 4
  | 'not-in-repository' // exit 5
  | 'failed' // exit 5
  | 'needs-confirmation' // exit 6 — reserved for cli-mutating (#65)
  | 'timeout' // exit 7
  | 'internal' // exit 70

/**
 * The exit code each error maps to. A `Record` over the union, so adding a code
 * without a mapping fails to compile — the exhaustiveness the test also asserts.
 */
const EXIT_CODE_BY_ERROR: Record<CLIErrorCode, number> = {
  usage: 2,
  'unknown-command': 2,
  unauthorized: 3,
  'rate-limited': 3,
  'app-not-running': 4,
  'not-in-repository': 5,
  failed: 5,
  'needs-confirmation': 6,
  timeout: 7,
  internal: 70,
}

/** The exit code for a successful command. */
export const ExitSuccess = 0

/** The process exit code for a given error. */
export function exitCodeForError(code: CLIErrorCode): number {
  return EXIT_CODE_BY_ERROR[code]
}

export type CLIArgValue = string | number | boolean | ReadonlyArray<string>

export interface ICLIRequest {
  readonly protocol: number
  /** A uuid, generated by the CLI, correlating the response. */
  readonly id: string
  /** From `endpoint.json`. Never logged, never echoed back. */
  readonly token: string
  /** `'ping'`, `'context list'`, … — resolved against the registry. */
  readonly command: string
  readonly args: Readonly<Record<string, CLIArgValue>>
  /** Absolute, resolved by the CLI. Untrusted — may come from an injected agent. */
  readonly cwd: string
  readonly client: { readonly name: string; readonly version: string }
}

export interface ICLIError {
  readonly code: CLIErrorCode
  readonly message: string
  readonly hint?: string
}

export type ICLIResponse =
  | {
      readonly protocol: number
      readonly id: string
      readonly ok: true
      readonly data: unknown
      readonly warnings?: ReadonlyArray<string>
    }
  | {
      readonly protocol: number
      readonly id: string
      readonly ok: false
      readonly error: ICLIError
    }

/** Written to `${userData}/cli/endpoint.json`, mode 0600, on every app start. */
export interface ICLIEndpoint {
  readonly protocol: number
  readonly transport: 'unix' | 'pipe'
  readonly path: string
  readonly token: string
  readonly appVersion: string
  readonly pid: number
  readonly startedAt: number
}

/** Build an `ok: false` response for an error — the one place error envelopes are shaped. */
export function errorResponse(
  id: string,
  code: CLIErrorCode,
  message: string,
  hint?: string
): ICLIResponse {
  const error: ICLIError =
    hint === undefined ? { code, message } : { code, message, hint }
  return { protocol: CLIProtocolVersion, id, ok: false, error }
}

/** Build an `ok: true` response. */
export function okResponse(
  id: string,
  data: unknown,
  warnings?: ReadonlyArray<string>
): ICLIResponse {
  return warnings === undefined || warnings.length === 0
    ? { protocol: CLIProtocolVersion, id, ok: true, data }
    : { protocol: CLIProtocolVersion, id, ok: true, data, warnings }
}

/** One NDJSON line: the JSON plus the terminating newline the framing needs. */
export function encodeLine(value: ICLIRequest | ICLIResponse): string {
  return JSON.stringify(value) + '\n'
}

/**
 * The result of reading a framed line: either the parsed value, or a reason it
 * could not be — never a thrown error. `too-large` is decided by byte length
 * *before* `JSON.parse`, so an oversized line is never parsed.
 */
export type DecodeResult<T> =
  | { readonly kind: 'ok'; readonly value: T }
  | { readonly kind: 'too-large' }
  | { readonly kind: 'malformed' }

function decodeLine<T>(line: string): DecodeResult<T> {
  if (Buffer.byteLength(line, 'utf8') > MaxRequestBytes) {
    return { kind: 'too-large' }
  }
  try {
    return { kind: 'ok', value: JSON.parse(line) as T }
  } catch {
    return { kind: 'malformed' }
  }
}

/** Decode a request line (server side). Enforces the frame limit before parsing. */
export function decodeRequest(line: string): DecodeResult<ICLIRequest> {
  return decodeLine<ICLIRequest>(line)
}

/**
 * Decode a response line (CLI side). A malformed or oversized response becomes an
 * `internal` error response rather than a throw, so the CLI always has an
 * envelope to render and an exit code to return.
 */
export function decodeResponse(line: string, id: string): ICLIResponse {
  const result = decodeLine<ICLIResponse>(line)
  if (result.kind === 'ok') {
    return result.value
  }
  const reason =
    result.kind === 'too-large'
      ? 'The response from Blackfin exceeded the size limit.'
      : 'The response from Blackfin could not be parsed.'
  return errorResponse(id, 'internal', reason)
}

/**
 * Whether a request's protocol is the one we speak. On mismatch the message
 * names *both* versions, so an agent on a newer or older build knows which way
 * to move.
 */
export function checkProtocol(
  protocol: number
): { readonly ok: true } | { readonly ok: false; readonly message: string } {
  if (protocol === CLIProtocolVersion) {
    return { ok: true }
  }
  return {
    ok: false,
    message:
      `This Blackfin speaks CLI protocol ${CLIProtocolVersion}, but the ` +
      `request used protocol ${protocol}. Update whichever is older.`,
  }
}

/**
 * Validate an untrusted `endpoint.json` shape into an `ICLIEndpoint`, or `null`.
 * Pure — the caller does the file read and passes the parsed JSON. Never throws.
 */
export function parseEndpoint(value: unknown): ICLIEndpoint | null {
  if (typeof value !== 'object' || value === null) {
    return null
  }
  const e = value as Record<string, unknown>
  if (
    typeof e.protocol !== 'number' ||
    (e.transport !== 'unix' && e.transport !== 'pipe') ||
    typeof e.path !== 'string' ||
    e.path.length === 0 ||
    typeof e.token !== 'string' ||
    e.token.length === 0 ||
    typeof e.appVersion !== 'string' ||
    typeof e.pid !== 'number' ||
    typeof e.startedAt !== 'number'
  ) {
    return null
  }
  return {
    protocol: e.protocol,
    transport: e.transport,
    path: e.path,
    token: e.token,
    appVersion: e.appVersion,
    pid: e.pid,
    startedAt: e.startedAt,
  }
}
